In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,StratifiedKFold,GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score, accuracy_score
from sklearn.ensemble import VotingClassifier

In [6]:
cancer = pd.read_csv("D:/onkar_cdac/C-DAC/PML/PML/Files_by_sir/5. PML/1. Day wise Study Material/Cases/Wisconsin/BreastCancer.csv",index_col=0)

In [7]:
cancer

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...
1369821,10,10,10,10,5,10,10,10,7,Malignant
1371026,5,10,10,10,4,10,5,6,3,Malignant
1371920,5,1,1,1,2,1,3,2,1,Benign
8233704,4,1,1,1,1,1,2,1,1,Benign
13454352,1,1,3,1,2,1,2,1,1,Benign

In [8]:
dum_cancer = pd.get_dummies(cancer, drop_first=True)

In [9]:
dum_cancer

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class_Malignant
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,0
63375,9,1,2,6,4,10,7,7,2,1
76389,10,4,7,2,2,8,6,1,1,1
95719,6,10,10,10,8,10,7,10,7,1
128059,1,1,1,1,2,5,5,1,1,0
...,...,...,...,...,...,...,...,...,...,...
1369821,10,10,10,10,5,10,10,10,7,1
1371026,5,10,10,10,4,10,5,6,3,1
1371920,5,1,1,1,2,1,3,2,1,0
8233704,4,1,1,1,1,1,2,1,1,0
13454352,1,1,3,1,2,1,2,1,1,0

In [10]:
X = dum_cancer.drop('Class_Malignant', axis=1)
y = dum_cancer['Class_Malignant']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                              stratify=y, random_state=2023)

In [12]:
clf = DecisionTreeClassifier(random_state=2023)
nb = GaussianNB()
svm = SVC(probability=True, random_state=2023, kernel='linear')

In [13]:
models = [('Tree', clf),('Naive', nb),('SVM', svm)]

In [14]:
voting = VotingClassifier(models, voting='soft')
voting.fit(X_train, y_train)

VotingClassifier(estimators=[('Tree',
                              DecisionTreeClassifier(random_state=2023)),
                             ('Naive', GaussianNB()),
                             ('SVM',
                              SVC(kernel='linear', probability=True,
                                  random_state=2023))],
                 voting='soft')

In [15]:
y_pred = voting.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9333333333333333

In [16]:
y_pred_prob = voting.predict_proba(X_test)[:,1]
print(roc_auc_score(y_test, y_pred_prob))

0.9861111111111112